### ISSUE TITLE
all works,but the video frame is low

### ISSUE THREAD

**Issue by cvtendent** [leadedge/SpoutVideoPlayer#1]
in vs2022  x64 debug mode,there will be errors:
'GCL_HCURSOR': undeclared identifier
'GCL_HICON': undeclared identifier
after redifine it as:
#define GCL_HCURSOR         (-12)
#define GCL_HICON           (-14)
the process go through.but the video frame is play in a low framerate,the audio is play well.
the release version that downloaded from this project works well,framerate is good.
Any advise?

**Comment by leadedge** [comment]
This project has not been updated for a while. Try changing GCL_HCURSOR to GCLP_HCURSOR and GCL_HICON to GCLP_HICON.

The slow playback is very strange. What version of Openframeworks are you using? It might have something to do with the latest version of Openframeworks, the Klite codecs and perhaps Visual Studio 2022 build. Could you please test the Openframeworks example Examples > Video > videoPlayerExample. This uses a sample video file "fingers.mov". Try that with SpoutVideoPlayer as well.

I don't have the Klite codecs installed at the moment but will test the project over the next few days.

**Comment by cvtendent** [comment]
> This project has not been updated for a while. Try changing GCL_HCURSOR to GCLP_HCURSOR and GCL_HICON to GCLP_HICON.

Yeah,this also works.



> The slow playback is very strange. What version of Openframeworks are you using? It might have something to do with the latest version of Openframeworks, the Klite codecs and perhaps Visual Studio 2022 build. Could you please test the Openframeworks example Examples > Video > videoPlayerExample. This uses a sample video file "fingers.mov". Try that with SpoutVideoPlayer as well.

I try the "fingers.mov",it can be played smoothly.As it is low resolution video,so I try some other low resolution low bitrate videos,they can also played smoothly.But with the increase of resolution,from 320 to 720 and 1080,the framerate get lower and lower.I work with Openframeworks version 0.11.2. K-lite is also the newest that can be downloaded from their website.
As the released version that downlaod from here works well with high resolution video,I think it maybe the Openframeworks version.Could you tell which Openframeworks version you used？I will make a try.

**Comment by leadedge** [comment]
The release version is built using Openframeworks 11.0 and Visual Studio 2017. I will rebuild the project with Openframeworks 11.2 and Visual Studio 2022 and will install the latest Klite pack over the weekend.

This sounds like a CPU issue. Is the speed increased if you disable both Spout and NDI output?

**Comment by cvtendent** [comment]
> This sounds like a CPU issue. Is the speed increased if you disable both Spout and NDI output?

My CPU is AMD Ryzen 2700，which is 8 core 16 threads, i think power enough to play 1080p video.
I set an 32-bit Visual Studio 2017 in VMware Windows 10 32-bit. And build it with Openframework 0.11.0. The framerate still low. Disable both NDI and Spout do not make any difference.

**Comment by osayanq** [comment]
> > This sounds like a CPU issue. Is the speed increased if you disable both Spout and NDI output?
> 
> My CPU is AMD Ryzen 2700，which is 8 cores 16 threads,I think power enough to play 1080p video.Turn off NDI and Spout do not make any difference.
 I set an 32-bit Visual Studio 2017 in VMware Windows 10 32-bit. And build it with Openframework 0.11.0. The framerate still low.

**Comment by leadedge** [comment]
I think it's an Openframeworks problem. 1920x1080 works OK, but 4K h264 video is very slow. The same movie plays fine with VLC.

However, there's a significant improvement with "mov" format rather than "mp4" and that's worth a try. I will still look at updating the project for VS2022.

There is a possibility with the [HAP codec addon](https://github.com/bangnoise/ofxHapPlayer). The example works very well at 4K. The code required is different though.

The cost of commercial software can be prohibitive, but I recommend [Magic Music Visuals](https://magicmusicvisuals.com/) as an inexpensive solution with Spout output. There's a free demo to give it a good workout.

**Comment by leadedge** [comment]
FYI. 

The project is updated for OpenFrameworks 11.2 and Visual Studio 2022 and tested with K-Lite codec pack 16.9.8.

The code has been revised to optimize performance. Movie pixel format is set to RGBA rather than remaining as default RGB. 

For NDI,  sender format is set to to NDIlib_FourCC_video_type_RGBX and send of movie pixels directly.

For Spout, the movie texture is attached to an fbo with internal format RGBA and send of the fbo texture.

The DirectShow codecs of the K-Lite codec package not seem to perform as well as VLC or FFmpeg, but addons available for these are out of date. The other possibility is using the HAP codec but that limits to HAP encoded movies. I had a dual setup at one time but it became too complicated and I removed it.

The repository achieves the purpose of making the code available for review, and the resulting application is useful. It works quite well with 1920x1080 videos but 4k videos fail to load.
